jumphosts:  
  hosts:
    jumphost:
      hot_ip: 10.0.0.211
      hostname: jumphost
        
master:
  hosts:
    server:
      ip: 10.0.0.212
      hostname: k8_server
        
workers:
  hosts:
    k8_worker_0:
      ip: 10.0.0.213
      hostname: k8_worker_0

    k8_worker_1:
      ip: 10.0.0.214
      hostname: k8_worker_1
